### ISSUE TITLE
To do list - Data

### ISSUE THREAD

**Issue by kimm00** [OSS-TeamProjectt/IT-MBTI#11]
### Tasks to Complete
1. Create Survey Questions
   - [x] Write 10-15 survey questions.
   - [x] Provide 3-4 options for each question.
   - [x] Map each option to corresponding results.

2. Prepare Survey Result Data
   - [x] Write cat type recommendations (e.g., "Calm Russian Blue").
   - [x] Write professor recommendations.
   - [x] Create job type recommendations.
   - [x] Add brief descriptions for each job type.

3. Structure Data in JSON Format
   - [x] Create survey questions in JSON format.
   - [x] Create result data in JSON format.
   - [x] Validate and refine the data structure.

**Comment by kimm00** [comment]
1. 당신은 새로운 사람들과의 만남이 즐겁고 에너지가 생깁니까?
* 예 / 아니오
예 -> E (팀워크 중요 / 마케팅 전문가, 이벤트 플래너, 영업직)
아니오 -> I (혼자 집중 / 소프트웨어 개발자, 연구원 작가)

2. 계획을 세우는 것보다 즉흥적으로 행동하는 것이 더 좋습니까?
* 예 / 아니오
예 -> P (유연성 중요 / 디자이너, 작가, 프리랜서)
아니오 -> J (체계적이고 규칙적 / 프로젝트 매니저, 변호사, 회계사)

3. 당신은 일을 시작하기 전에 철저히 조사하고 준비하는 것을 선호합니까?
* 예 / 아니오
예 -> J (계획적이고 분석적 / 데이터 분석가, 경영 컨설턴트, 교수)
아니오 -> P (창의적이고 유연함 / 예술가, 광고 기획자, 여행 가이드)

4. 논리적이고 객관적인 결정을 내리는 것이 어렵지 않습니까?
* 예 / 아니오
예 -> T (분석적이고 문제 해결 중심 / 엔지니어, 프로그래머, 재무 분석가)
아니오 -> F (사람 중심 / 심리 상담사, 사회복지사, HR 관리자)

5. 상상력과 창의력이 필요한 작업에 더 흥미를 느낍니까?
* 예 / 아니오
예 -> N (창의적이고 혁신적 / UI/UX 디자이너, 광고 전문가, 창업가)
아니오 -> S (실용적이고 세부적 / 기술자, 약사, 간호사)

6. 결정을 내릴 때 개인적인 가치와 감정을 중요하게 여깁니까?
* 예 / 아니오
예 -> F (인간 중심 / 교사, 코치, NGO 활동가)
아니오 -> T (r결과 중심 / 법률가, 데이터 과학자, 금융 전문가)

7. 친구들과 함께 시간을 보내는 것이 혼자만의 시간을 가지는 것보다 더 좋습니까?
* 예 / 아니오
예 -> E (협력적이고 활동적 / 홍보 담당자, 이벤트 매니저, 외교관)
아니오 -> I (독립적이고 깊이 있는 / 작가, 연구 과학자, 아티스트)

8. 미래에 대한 가능성을 탐구하는 것을 좋아합니까, 아니면 현재의 사실과 실질적인 정보를 더 중시합니까?
* 예 / 아니오
예-> N (gu혁신적이고 비전 중심 / 스타트업 창업가, 소프트웨어 디자니어, 작가)
아니오 -> S (실질적이고 안정적 / 물리치료사, 건축가, 공학자)

9. 갈등 상황에서 당신은 중재자 역할을 잘 수행합니까?
* 예 / 아니오
예-> F (사람 중심의 문제 해결 / HR 전문가, 상담가, 팀 리더)
아니오 -> T (논리적 해결 중심 / IT 전문가, 시스템 관리자, 법률 컨설턴트)

10. 마감 기한이 닥쳐야 작업을 시작하는 편입니까?
* 예 / 아니오
예 -> P (유연하고 창의적 / 작가, 예술가, 콘텐츠 크리에이터)
아니오 -> J (시간 관리가 중요 / 프로젝트 매니저, 컨설턴트, 관리자)

**Comment by kimm00** [comment]
**JSON Data - Result**

{
  "results": [
    {
      "type": "INTJ",
      "description": "독립적이고 분석적인 전략가입니다.",
      "recommendedJobs": ["Data Scientist", "Software Developer", "Consultant"]
    },
    {
      "type": "ENFP",
      "description": "창의적이고 사람들과 소통을 즐기는 활동가입니다.",
      "recommendedJobs": ["Marketing Specialist", "Event Planner", "Entrepreneur"]
    },
    {
      "type": "ISFJ",
      "description": "친절하고 책임감 있는 수호자입니다.",
      "recommendedJobs": ["Nurse", "Social Worker", "Teacher"]
    },
    {
      "type": "ESTP",
      "description": "실용적이고 활동적인 기업가입니다.",
      "recommendedJobs": ["Sales Representative", "Business Consultant", "Pilot"]
    }
  ]
}

**Comment by shinh09** [comment]
결과창
<cat유형>
-고양이 유형: 샴
-진로유형: “You are a Code Artist, Fronted Developer ”
-진로 유형 짧게 소개: 당신은 00과 00이 높은 유형입니다.

<디테일>
-하는 일: 모바일 앱 개발자는 스마트폰이나 태블릿PC 등 모바일 기기에서 사용되는 소프트웨어인 모바일 애플리케이션을 개발하고 수정하는 일을 합니다. 국내외의 모바일 앱 개발 흐름 및 우리나라 사람들의 모바일 기기 이용 특성에 적합한 애플리케이션을 기획하고 개발합니다.
-관련 직업 : 시스템소프트웨어개발자, 컴퓨터하드웨어 기술자 및 연구원, 보건의료정보관리자, 고객관리시스템(CRM)전문가, 클라우드 시스템 엔지니어
-핵심 능력: 수리.논리력
-태그: 프로그래머, 소프트웨어, 개발자, 디자인

<그래프>
7가지 유형

<교수>
유형 당 2분

<추천기술>
유형 당 3가지 키워드만

**Comment by kimm00** [comment]
**ISTJ - 고독한 러시안 블루형**
특징: 차분하고 신중하며, 논리적 사고와 철저한 계획을 선호.
직업 매칭: Backend Developer - Invisible Maestro
데이터베이스 설계와 서버 구조 최적화에 강한 책임감을 발휘.
문제 해결 능력과 효율적인 코딩으로 시스템 성능을 향상.

**ISFJ - 따뜻한 브리티시 쇼트헤어형**
특징: 헌신적이고 친절하며, 타인을 돕는 것을 좋아함.
직업 매칭: Data Analyst - Detective of Numbers
데이터를 분석하고 유용한 통찰을 도출하여 조직에 기여.
세심한 주의력으로 문제 해결과 데이터 시각화를 수행.

**INFJ - 신비로운 샤트룩스형**
특징: 깊은 통찰력과 직관을 바탕으로, 창의적이고 이상적.
직업 매칭: IT Strategy Consultant - Architect of the Future
IT 솔루션 설계로 비즈니스 문제를 해결하며 조직의 목표를 달성.
기술적 지식과 비즈니스 통찰력을 결합해 혁신적인 전략을 제안.

**INTJ - 독립적인 벵갈형**
특징: 전략적이고 분석적이며, 효율성과 계획을 중시.
직업 매칭: DevOps Engineer - Automation Magician
시스템 자동화 및 CI/CD 파이프라인 설계를 통해 개발과 운영의 협력을 극대화.
장기적인 관점으로 효율적이고 견고한 시스템을 구축.

**ISTP - 냉철한 오리엔탈 숏헤어형**
특징: 실용적이고 분석적이며, 문제 해결 능력이 뛰어남.
직업 매칭: Frontend Developer - Glamorous Stage Director
HTML, CSS, JavaScript로 직관적이고 사용자 친화적인 인터페이스 구축.
유연한 사고로 디자인과 사용자 경험 개선에 중점을 둠.

**ISFP - 예술적인 스코티시 폴드형**
특징: 부드럽고 예술적이며, 섬세한 감각을 소유.
직업 매칭: UI/UX Designer - Creative Dream Maker
직관적인 네비게이션과 창의적인 디자인으로 사용자 경험을 향상.
색상, 레이아웃, 타이포그래피와 같은 시각적 요소를 활용.

**INFP - 몽상적인 라가머핀형**
특징: 상상력이 풍부하고 감정적인 유대를 중요시함.
직업 매칭: Writer - Visionary Storyteller
독창적이고 감성적인 스토리텔링으로 사람들의 마음을 움직임.
깊이 있는 창의적 작업을 통해 자신만의 색깔을 표현.

**INTP - 호기심 많은 스핑크스형**
특징: 논리적이고 호기심이 많으며, 새로운 아이디어를 탐구.
직업 매칭: Data Analyst - Detective of Numbers
데이터를 기반으로 통찰력 있는 결정을 내리고, 창의적인 솔루션을 제시.
분석 도구와 기술을 활용해 새로운 패턴과 기회를 발견.

**ESTP - 장난꾸러기 아비시니안형**
특징: 활동적이고 사교적이며, 빠른 판단과 실행력을 지님.
직업 매칭: Business Development Manager - Explorer of Opportunities
시장 트렌드 분석과 전략 수립을 통해 비즈니스 기회를 발굴.
협력과 네트워킹으로 프로젝트를 성공적으로 완수.

**ESFP - 활발한 시암형**
특징: 외향적이고 즐거움을 추구하며, 사교성이 뛰어남.
직업 매칭: Event Planner - Social Butterfly
창의적인 이벤트 기획과 실행으로 사람들을 모으고 분위기를 고조.
다양한 아이디어로 축제와 행사를 성공적으로 진행.

**ENFP - 자유로운 터키시 앙고라형**
특징: 열정적이고 창의적이며, 새로움을 추구.
직업 매칭: UI/UX Designer - Creative Dream Maker
창의적인 아이디어와 혁신적인 디자인으로 독창적인 사용자 경험 제공.
직관적인 탐구와 비전을 바탕으로 디자인 솔루션을 제안.

**ENTP - 창의적인 사바나형**
특징: 대담하고 논쟁을 즐기며, 새로운 가능성을 탐구.
직업 매칭: Entrepreneur - Visionary Innovator
창업과 혁신적 아이디어를 통해 새로운 가치를 창출.
끊임없는 도전과 실험으로 시장의 변화를 선도.

**ESTJ - 책임감 있는 메인쿤형**
특징: 실용적이고 조직적이며, 리더십이 뛰어남.
직업 매칭: Project Manager - Organized Leader
팀을 관리하고 프로젝트를 체계적으로 이끌어 성공적인 결과를 도출.
현실적인 접근법과 효율적인 자원 관리로 목표를 달성.

**ESFJ - 친근한 버만형**
특징: 사교적이고 헌신적이며, 인간관계를 중시.
직업 매칭: HR Manager - Compassionate Coordinator
직원들과의 신뢰를 구축하며 팀워크를 강화.
사람 중심의 접근법으로 조직 내 긍정적인 분위기를 조성.

**ENFJ - 리더십 있는 라가돌형**
특징: 카리스마와 헌신으로 팀을 이끄는 리더십.
직업 매칭: Team Leader - Inspiring Motivator
팀의 잠재력을 끌어내며 협력을 통해 목표를 달성.
긍정적인 에너지를 주도하며 모두가 성장할 수 있도록 격려.

**ENTJ - 전략적인 사바나형**
특징: 목표 지향적이고 리더십이 강하며, 체계적.
직업 매칭: IT Strategy Consultant - Architect of the Future
혁신적인 IT 전략과 비즈니스 통찰력으로 조직을 성공으로 이끎.
효율적인 계획과 실행으로 도전적인 목표를 달성.

**Comment by han3o1** [comment]
진로 유형: **UI/UX Designer - Creative Dream Maker**
고양이 유형: **예술적인 스코티시 폴드형**
진로 유형 소개: 창의적인 아이디어와 혁신적인 디자인으로 독창적인 사용자 경험을 제공합니다.
하는 일: 사용자 경험(UX) 리서치를 통해 사용자 요구사항과 행동 패턴을 분석하고, 이를 기반으로 와이어프레임과 프로토타입을 설계하여 초기 디자인 구상을 시각화합니다. 이후, 세부적인 사용자 인터페이스(UI)를 디자인하여 직관적이고 사용자 친화적인 디지털 환경을 제공합니다.
관련 직업: UX 디자이너, UI 디자이너, 서비스 디자이너, 제품 디자이너
핵심 능력: 창의력, 사용성 테스트 능력, 시각적 커뮤니케이션 스킬, 디자인 소프트웨어 활용 능력
교수: 
김자희 교수님 (텍스트 분석, 기술 트렌드 분석, 사용자 경험 디자인과 관련된 연구를 수행하며, UX/UI 설계와 기술 트렌드 분석에 중점을 둠.)
홍정식 교수님 (Explainable Data Mining 전문가로, 데이터 기반 UI/UX 최적화 및 사용자 행동 분석 연구를 수행함.)
추천 기술: Figma, Adobe Creative Suite, Sketch, 사용성 테스트 도구, 프로토타이핑 기술




진로 유형: **Frontend Developer - Glamorous Stage Director**
고양이 유형: **냉철한 오리엔탈 숏헤어형**
진로 유형 소개: 유연한 사고로 직관적이고 사용자 친화적인 인터페이스를 구축합니다.
하는 일: 웹사이트와 애플리케이션의 프론트엔드 개발을 통해 사용자 인터페이스(UI)를 구축하고, 백엔드 시스템과의 원활한 통합을 구현합니다. 또한, 다양한 디바이스에서 최적의 사용자 경험을 제공하기 위해 반응형 웹 디자인을 적용합니다.
관련 직업: 프론트엔드 개발자, 웹 개발자, UI 엔지니어
핵심 능력: 프레임워크 사용 능력, 반응형 디자인 구현 능력
교수: 
김우제 교수님 (소프트웨어공학 및 IT 서비스 분야 전문가로, 효율적인 사용자 인터페이스 개발과 관련된 기술 및 접근 방식 연구를 수행함.)
이영훈 교수님 (자연어처리와 추천시스템 연구를 통해 프론트엔드에서 사용자 맞춤형 서비스 구현에 기여함.)
추천 기술: HTML/CSS, JavaScript, React, Vue.js, Angular, TypeScript, Webpack, CSS preprocessors(Sass/Less)


진로 유형: **Backend Developer - Invisible Maestro**
고양이 유형: **고독한 러시안 블루형**
진로 유형 소개: 데이터베이스 설계와 서버 구조 최적화의 분야에서 효율적인 코딩으로 시스템의 성능을 향상시킵니다.
하는 일: 서버 개발을 통해 안정적인 시스템 환경을 구축하고, 데이터베이스를 효율적으로 관리하여 데이터의 저장 및 접근을 최적화합니다. 또한, API를 설계하고 구현하여 시스템 간의 원활한 통신을 지원하며, 보안을 강화하여 데이터와 시스템의 안전성을 확보합니다.
관련 직업: 백엔드 개발자, 데이터베이스 관리자(DBA), 시스템 엔지니어
핵심 능력: 프로그래밍 언어, 데이터베이스 관리, RESTful API 설계, 서버 성능 최적화
교수: 
권혁윤 교수님 (분산/클라우드 컴퓨팅 및 빅데이터 처리에 전문성을 보유하며, 서버 구조 설계 및 데이터 효율성을 중시함.)
심민규 교수님 (확률 과정론 및 금융 데이터 모델링을 통해 안정적이고 효율적인 백엔드 시스템 설계를 지원함.)
추천 기술: Java, Python, Docker, Kubernetes, Node.js, Django, MySQL, SQL, NoSQL


진로 유형: **DevOps Engineer - Automation Magician**
고양이 유형: **독립적인 벵갈형**
진로 유형 소개: 시스템 자동화 및 CI/CD 파이프라인 설계를 통해 개발과 운영의 협력을 극대화합니다.
하는 일: 자동화 스크립트를 작성해 반복 작업을 효율화하고, CI/CD 파이프라인을 설계해 소프트웨어 개발과 배포를 원활하게 만듭니다. 클라우드 환경을 체계적으로 관리하여 안정적이고 확장 가능한 시스템을 구축합니다.
관련 직업: 데브옵스 엔지니어, 시스템 관리자, 클라우드 엔지니어
핵심 능력: 클라우드 플랫폼(AWS, Azure, GCP), 스크립트 작성(Shell, Python), CI/CD 툴(Jenkins, GitHub Actions)
교수: 
안재경 교수님 (통신경영 및 정보통신기술평가를 전문으로 하며, IT 시스템 자동화와 운영 최적화 관련 기술을 연구함.)
이학연 교수님 (기술경영과 데이터 비즈니스를 기반으로 DevOps 프로세스 최적화 방안을 연구함.)
호수에 오브레곤 교수님 (스마트 제조와 에너지 분야를 중심으로, IT 시스템 자동화와 효율성 증진을 위한 연구를 전문으로 함.)
추천 기술: Terraform, Ansible, Jenkins, Kubernetes, AWS/GCP


진로 유형: **Data Analyst - Detective of Numbers**
고양이 유형: **호기심 많은 스핑크스형**
진로 유형 소개: 데이터를 기반으로 통찰력 있는 결정을 내리고, 다양한 분석 도구와 기술을 활용해 새로운 패턴과 기회를 발견합니다.
하는 일: 데이터를 다양한 출처에서 수집하여 체계적으로 정리하고, 품질 검증과 정제를 통해 분석 가능한 형태로 가공합니다. 이후 통계 분석 기법을 활용하여 데이터 내 숨겨진 패턴과 트렌드를 발견하고, 이를 통해 의미 있는 정보를 도출합니다. 이러한 분석 결과를 바탕으로 데이터 시각화 도구를 사용해 직관적이고 이해하기 쉬운 형태로 표현하여, 핵심 인사이트를 명확히 전달하고 데이터 기반 의사결정을 지원합니다.
관련 직업: 데이터 분석가, 비즈니스 분석가, 데이터 사이언티스트
핵심 능력: SQL, Python/R, 통계학, 데이터 시각화 도구(Tableau, Power BI)
교수: 
심재웅 교수님 (데이터마이닝 및 제조 데이터 분석 전문가로, 복잡한 데이터에서 통찰을 도출하며 분석 기법을 연구함.)
윤양인 교수님 (회계 금융 경제 데이터를 분석하고, 회계감사 및 빅데이터 기반 의사결정을 연구함.)
추천 기술: Python(Pandas, NumPy), SQL, Tableau, Power BI, R


진로 유형: **IT Strategy Consultant - Architect of the Future**
고양이 유형: **전략적인 사바나형**
진로 유형 소개: 기술적 지식과 비즈니스 통찰력을 결합해 조직의 목표를 달성할 혁신적인 전략을 제안합니다.
하는 일: 기술 로드맵을 수립하여 조직의 중장기적인 목표를 설정하고, 기술 도입과 발전의 구체적인 단계를 계획합니다. 이를 통해 비즈니스 목표에 부합하는 실행 가능한 전략을 제안하며, 각 기술의 도입 효과와 리스크를 면밀히 분석합니다. 또한, IT 솔루션을 심층적으로 평가하고 조직의 요구사항과 자원에 최적화된 구현 방안을 마련하여 효율성과 생산성을 극대화합니다.
관련 직업: IT 컨설턴트, 프로젝트 매니저, 기술 전략가
핵심 능력: 비즈니스 분석, IT 트렌드 이해, 문제 해결 능력, 프레젠테이션 스킬
교수: 
이학연 교수님 (기술경영과 데이터 비즈니스 전략 분야 전문가로, 비즈니스 목표를 달성하기 위한 IT 전략 개발에 중점을 둠.)
금영정 교수님 (기술 기획 및 서비스 기획을 전문으로, IT 전략과 서비스 최적화 방안을 연구함.)
추천 기술: Microsoft Office Suite(Excel, PowerPoint), Jira, 비즈니스 분석 도구


진로 유형: **Business Development Manager - Explorer of Opportunities**
고양이 유형: **장난꾸러기 아비시니안형**
진로 유형 소개: 시장 트렌드 분석과 전략 수립을 통해 비즈니스 기회를 발굴해 프로젝트를 성공으로 이끕니다.
하는 일: 시장 조사를 통해 업계 동향과 경쟁 구도를 분석하고, 고객의 니즈를 파악하여 비즈니스 기회를 발굴합니다. 이를 기반으로 신규 고객을 효과적으로 발굴하고, 장기적인 협력을 위한 전략적인 파트너십을 구축합니다. 또한, 매출 성장을 목표로 구체적인 전략을 설계하고 실행하며, 이를 통해 조직의 비즈니스 목표를 달성할 수 있도록 지원합니다.
관련 직업: 비즈니스 개발 관리자, 영업 관리자, 마케팅 전략가
핵심 능력: 커뮤니케이션 능력, 데이터 분석, 네트워킹 스킬, 협상력
교수: 
조남욱 교수님 (사회연결망 분석 및 비즈니스 프로세스 관리 연구를 수행하며, 비즈니스 기회 발굴과 전략적 실행을 지원함.)
김지표 교수님 (투자공학 및 의사결정 분석 전문가로, 데이터를 기반으로 한 사업 기회 창출과 전략 실행을 지원함.)
추천 기술: CRM 도구(Salesforce, HubSpot), 데이터 분석 툴, 프레젠테이션 소프트웨어
